site_name: GDD - Purrfect Kitten

extra_css:
  - css/purrfect-toc.css

theme:
  name: null
  custom_dir: mkdocs_dracula_theme
  favicon: images/Moninha.png   # 👈 agora seu site vai usar o gatinho!

nav:
  - Início: gdd_minc/index.md
